### ISSUE TITLE
Sites - Builder

### ISSUE THREAD

**Issue by mattbasta** [Pinecast/pinecast#139]
- [x] Finish presets for existing themes
- [x] Add three new presets for new themes
  - [x] Clarity
  - [x] Abide
  - [x] Sandwich
- [x] 5 button presets
- [x] 5 more color swatches
- [ ] 4 more font pairings
- [x] Support for dynamic page sizes (analysis of theme object in monolith)

# Editor

## Phase 1

- [x] Color scheme editor
- [x] Typography editor
- [x] Global styles editor (buttons, page)
- [x] Preset chooser
- [x] Embed widget chooser

Editor features:

- [x] Preview navigation
- [x] Preview viewport control
- [ ] Preset options

Preset options should allow the user to make basic adjustments to their site based on components chosen in the current theme.

- [x] Theme options `{colors: {}, fonts: {}, /* ... */ options: {/* ... */}}`; strongly typed
  - [x] Make embed widget theme an option
  - [x] Page width as an option
    - [x] Number (960, etc.)
    - [x] `-1` == full width
    - [x] Support in `prepareStyle()` for length types to accept `pageWidth`

## Phase 1.5

- [ ] Page editor
- [x] Asset manager (cover, logo, favicon, etc.)
- [x] Links editor
- [x] Settings dash
  - [x] Custom domain
  - [x] Directory links
    - [x] Apple Podcasts banner
  - [x] Custom domain

## Phase 2

- [ ] Ability to swap out major container styles
  - [ ] Page styles; page wrapper styles
  - [ ] Episode page style; episode page wrapper styles
- [ ] Ability to add and remove modules from header, body first page after prefix, and footer (with predefined modules)
- [ ] Ability to add and remove layouts from home
- [ ] Ability to set item style for layouts in home
