### ISSUE TITLE
Tip Jar enhancements

### ISSUE THREAD

**Issue by mattbasta** [Pinecast/pinecast#201]
- [ ] Make subscriptions page more friendly
  - Show recent tips for a subscriber account
  - Show current subscriptions
  - Show next tip date for current subscriptions
  - Accordion for subscriptions to allow cancellation of subscription (supersedes #185)
- [ ] Add combined private RSS feed
- [ ] On tip jar page, show minimum tip required for private content
- [ ] Allow payouts to a debit card instead of bank account
- [ ] Allow podcast owners to set a message to be shown on the tip jar (supersedes #186)
- [ ] Allow podcast owners to set a message to be shown after tipping (supersedes #186)
- [ ] Allow podcast owners to set a message to be sent via email after tipping
- [ ] Allow podcast owners to cancel subscriptions (supersedes #186)
